# Generated by Django 3.1.4 on 2020-12-23 15:07

import LandingPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, validators=[LandingPage.models.mycustomvalidator, LandingPage.models.val2])),
                ('image', models.ImageField(blank=True, null=True, upload_to='ServicesDetails/')),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
