# Generated by Django 3.1.4 on 2020-12-24 06:12

import LandingPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, validators=[LandingPage.models.mycustomvalidator, LandingPage.models.val2])),
                ('subtitle', models.TextField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='HomeSlider/')),
            ],
        ),
    ]
