# Generated by Django 3.1.4 on 2020-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
