# Generated by Django 3.1.4 on 2020-12-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_auto_20201224_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('nature', models.TextField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('value_of_work', models.FloatField(blank=True, null=True)),
                ('contract_period', models.IntegerField(blank=True, null=True)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_complete', models.DateField(blank=True, null=True)),
                ('per_of_complete', models.IntegerField(blank=True, null=True)),
                ('value_of_completework', models.FloatField(blank=True, null=True)),
                ('balance_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='descriptions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
