# Generated by Django 3.1.4 on 2020-12-24 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_auto_20201224_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.related.OneToOneField>/Pictures/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.projects')),
            ],
        ),
    ]
