# Generated by Django 3.1.4 on 2020-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0005_projectspictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
