# Generated by Django 3.1.4 on 2020-12-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_projects_coverimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='coverimg',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='nature',
            new_name='nature_of_work',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='per_of_complete',
            new_name='percentage_of_complete',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='value_of_completework',
            new_name='value_of_completed_work',
        ),
    ]
