# Generated by Django 3.1.4 on 2020-12-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0009_auto_20201225_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspictures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Projects/Pictures/'),
        ),
        migrations.AlterField(
            model_name='projectspictures',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.projects'),
        ),
    ]
