# Generated by Django 3.1.4 on 2021-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0011_staffcategory_staffsubcategory_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
