# Generated by Django 3.1.4 on 2021-01-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0013_homepageextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageextra',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Home/Images/'),
        ),
    ]
