# Generated by Django 3.1.4 on 2021-01-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0014_auto_20210104_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(null=True, upload_to='Certificate/')),
            ],
        ),
        migrations.AlterField(
            model_name='homepageextra',
            name='numberofconst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepageextra',
            name='numberofemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepageextra',
            name='numberofpart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepageextra',
            name='numberofprj',
            field=models.IntegerField(default=0),
        ),
    ]
