# Generated by Django 3.1.4 on 2021-01-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0015_auto_20210106_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=64)),
                ('vehicleno', models.CharField(max_length=64)),
                ('make', models.CharField(max_length=64)),
                ('year', models.CharField(max_length=64)),
            ],
        ),
    ]
