# Generated by Django 3.1.4 on 2021-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20210103_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='is_responded',
            field=models.BooleanField(null=True),
        ),
    ]
