# Generated by Django 3.1.4 on 2021-01-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_quotationrequest_is_responded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
