# Generated by Django 3.1.4 on 2021-01-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20210103_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='respmessage',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='respmessage',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
